namespace LpjGuess.Frontend.Interfaces.Views;

/// <summary>
/// Represents a view component that can be displayed in a grid layout.
/// </summary>
public interface IValueGeneratorView : INamedView
{
    /// <summary>
    /// User-facing kind of variation.
    /// </summary>
    string Kind { get; }

    /// <summary>
    /// Fully-qualified target summary.
    /// </summary>
    string Target { get; }

    /// <summary>
    /// Compact summary of the generated values or scenarios.
    /// </summary>
    string ValueSummary { get; }

    /// <summary>
    /// Number of generated levels.
    /// </summary>
    int LevelCount { get; }

    /// <summary>
    /// The values which would be generated by the model displayed by this view.
    /// </summary>
    IEnumerable<string> Values { get; }

    /// <summary>
    /// Whether all values are being displayed.
    /// </summary>
    bool AllValues { get; }
}
