namespace LpjGuess.Frontend.Interfaces.Views;

/// <summary>
/// Represents a view component that can be displayed in a grid layout.
/// </summary>
public interface IValueGeneratorView : INamedView
{
    /// <summary>
    /// The values which would be generated by the model displayed by this view.
    /// </summary>
    IEnumerable<string> Values { get; }

    /// <summary>
    /// Whether all values are being displayed.
    /// </summary>
    bool AllValues { get; }
}
